- apps/postgres-new/components/chat.tsx
- apps/postgres-new/components/workspace.tsx
Hides the app on non-desktop devices until we can sort out mobile-specific bugs.
> feat: hide mobile

- apps/postgres-new/components/sidebar.tsx
Bug fix
- Sign out button appears even when the current state is non-logged in and the sidebar is collapsed
- Conditionally hide the signout button when the sidebar is collapsed
> fix(sidebar): :bug: conditionally hide signout button when collapsed

- apps/postgres-new/components/app-provider.tsx
- apps/postgres-new/components/chat.tsx
- apps/postgres-new/components/sidebar.tsx
- apps/postgres-new/data/deploy-waitlist/deploy-waitlist-query.ts
Right now when you tap "New Database" when signed out, nothing happens.
This PR adds a "sign in" dialog that appears in two scenarios:
- you click the "New Database" button when signed out
- you click on a new "Why do I need to sign in" link
> feat: sign in dialog when clicking 'new database'

- apps/postgres-new/app/api/chat/route.ts
- apps/postgres-new/lib/tools.ts
In an ideal world, we send as much context to the LLM as possible so that it has the most amount of information to help respond to your questions/tasks. Unfortunately token costs grow quadratically for every message added to the chat, since you need to send all previous messages each time.
To prevent token costs from blowing out of proportion, we can limit the max number of previous messages to send to the LLM as context each request.
_Important:_ this does not mean the actual message history is limited on the frontend. This is strictly referring to the sliding window of the past X messages being sent to the LLM as context each time.
This PR sets this message context limit to 30 messages. The consequence of this change is that the model will have no memory of messages older than 30 …
> feat: limit message context sent to llm

- apps/postgres-new/.env.example
- apps/postgres-new/README.md
- apps/postgres-new/app/api/chat/route.ts
- apps/postgres-new/components/app-provider.tsx
- apps/postgres-new/components/chat.tsx
- apps/postgres-new/components/workspace.tsx
- apps/postgres-new/docker-compose.yml
- apps/postgres-new/package.json
- package-lock.json
- package.json
As with any free product, most users use it as intended, but a small number take advantage and abuse it.
This update introduces standard rate limiting to the app. Current limits are:
- **Input tokens:** 1000000/30m
- **Output tokens:** 10000/30m
After reaching this limit the user will see:
Until the next reset period.
> feat: rate limits

- apps/postgres-new/components/layout.tsx
Adds a banner at the top of the page notifying about the rename:
Clicking "Why?" opens the following modal:
> Adds banner explaining the rename

- apps/postgres-new/components/layout.tsx
Temporarily hide the rename banner until we are ready to show it.
> feat: temporarily hide rename banner

- apps/postgres-new/components/chat.tsx
- https://github.com/supabase-community/postgres-new/issues/83
Bug fix
Currently, when typing in languages that use Input Method Editors (IMEs) such as Japanese, pressing the Enter key to confirm the IME conversion unintentionally sends the message. This occurs because the system doesn't distinguish between normal Enter key presses and those used for IME conversion confirmation.
This PR adds an `isComposing` check to the `keydown` event handler. This prevents the message from being sent while the user is still in the process of IME composition. Here's a snippet of the modified code:
```ts
onKeyDown={(e) => {
if (!(e.target instanceof HTMLTextAreaElement)) {
return
}
if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
// ... rest of the handler
```
This change ensures …
> fix(chat): prevent Enter key action during IME composition

- apps/browser-proxy/src/index.ts
- apps/browser-proxy/src/pg-dump-middleware/constants.ts
- apps/browser-proxy/src/pg-dump-middleware/get-extension-membership-query.ts
- apps/browser-proxy/src/pg-dump-middleware/get-extensions-query.ts
- apps/browser-proxy/src/pg-dump-middleware/pg-dump-middleware.ts
- apps/browser-proxy/src/pg-dump-middleware/utils.ts
- apps/browser-proxy/src/tcp-server.ts
- apps/browser-proxy/src/websocket-server.ts
- apps/postgres-new/package.json
- package-lock.json
I implemented a "middleware" which :
- detects if `pg_dump` initiated a connection through the `application_name=pg_dump` in the Startup message.
- listen to both client and server message to detect and patch the right query results.
The two queries we're interested in are:
- [GetExtensions](https://github.com/postgres/postgres/blob/a19f83f87966f763991cc76404f8e42a36e7e842/src/bin/pg_dump/pg_dump.c#L5834-L5837)
- [GetExtensionMembership](https://github.com/postgres/postgres/blob/a19f83f87966f763991cc76404f8e42a36e7e842/src/bin/pg_dump/pg_dump.c#L18173-L18178)
I looked at pg_dump code from v15 to v17 and the queries definitions are the same across all these versions so we can safely detect them.
The logic is:
- We detect the GetExtensions query
- We wait for its result from which we …
> Fix pg_dump for databases created with PGlite < v0.2.9

- README.md
Updates the root README with the new site name: database.build.
Leaving `./apps/postgres-new` as-is for now, since we've already renamed this to `web` in some feature branches.
> docs: update readme with site rename

- README.md
- apps/postgres-new/app/export/page.tsx
- apps/postgres-new/app/import/page.tsx
- apps/postgres-new/components/layout.tsx
Adjusts wording around why postgres.new was renamed to database.build.
> feat: site rename wording tweaks

- apps/postgres-new/.env.example
- apps/postgres-new/components/app-provider.tsx
- apps/postgres-new/components/layout.tsx
Adds a **Live Share** banner to introduce the new live share functionality.
https://github.com/user-attachments/assets/79613917-ff3a-4f2a-b986-c4af037d0b9b
Also removes the "preview banner" which is no longer needed.
> Live share banner

- apps/postgres-new/components/chat.tsx
- package-lock.json
Adds FAQs for the Live Share feature.
> Live share FAQs

- apps/postgres-new/components/ide.tsx
- apps/postgres-new/components/tools/csv-export.tsx
- apps/postgres-new/components/tools/csv-import.tsx
- apps/postgres-new/components/tools/executed-sql.tsx
- apps/postgres-new/lib/hooks.ts
- apps/postgres-new/lib/sql-util.ts
- apps/postgres-new/package.json
- package-lock.json
The SQL formatter we use (`sql-formatter`) crashes the page if it encounters SQL that it didn't expect. There are a few edge cases where valid SQL causes the formatter to throw an error. Since we called `format()` inside a React `useMemo()`, the component rendering failed and caused the page to crash.
<details>
<summary>Example query that caused `sql-formatter` to throw</summary>
```sql
WITH streaks AS (
SELECT 
time,
close,
LAG(close) OVER (ORDER BY time) AS prev_close,
CASE WHEN close > LAG(close) OVER (ORDER BY time) THEN 1 ELSE 0 END AS is_green
FROM nse_trent
),
marked_streaks AS (
SELECT 
time,
close,
is_green,
SUM(CASE WHEN is_green = 0 THEN 1 ELSE 0 END) OVER (ORDER BY time) AS streak_id
FROM streaks
),
winning_streaks AS (
SELECT 
MIN(time) AS start_date,
MAX(time) AS end_date, …
```
> Fix SQL formatter causing page crashes

- apps/postgres-new/components/app-provider.tsx
- apps/postgres-new/lib/pg-wire-util.ts
Monitors wire protocol messages during a Live Share session and automatically updates the schema UI to reflect the current state.
In order to update the schema UI, we need to query the PGlite instance (via pg-meta) to get the latest tables/columns. Since this requires executing SQL against the same PGlite instance that Live Share is communicating with, we need to be careful not to run this when the user is in the middle of set of protocol messages (eg. extended queries).
We update the UI after detecting a `ReadyForQuery` response from PGlite, which indicates that the current set of protocol messages have completed and a fresh query is safe to execute. We also ensure that the connection is not in the middle of a transaction by checking a transaction status flag sent with the …
> Refresh schema UI as live share queries executed

- apps/postgres-new/lib/db/index.ts
When importing databases into database.build (ie. from postgres.new), tool invocations fail to import correctly. This is related to changes to how PGlite serialized JSON columns in 0.2.7 vs. 0.2.8 (ie. you should no longer manually serialize JSON content via `JSON.stringify()` when saving data into a column - if you do, it will literally import as a string).
This was [caught](https://github.com/supabase-community/postgres-new/pull/103/commits/49da099d2b800807e3d34f143f94cbb65ede979c) in the Live Share branch at the time, but not in the export/import branch. This patch fixes the import logic to also remove `JSON.stringify()`.
> Fix tool invocations in message import

- apps/postgres-new/components/chat.tsx
- apps/postgres-new/components/ide.tsx
- apps/postgres-new/components/tools/index.tsx
- apps/postgres-new/components/tools/sql-import.tsx
- apps/postgres-new/components/tools/sql-request.tsx
- apps/postgres-new/lib/files.ts
- apps/postgres-new/lib/hooks.ts
- apps/postgres-new/lib/tools.ts
Users can now drop or import `.sql` files into the chat.
The DDL statements executed as part of the `.sql` file will be recorded as migrations.
Demo:
https://github.com/user-attachments/assets/abf5557b-c0af-4510-b671-64ef51d3a10a
> feat: import sql files

- apps/postgres-new/app/api/chat/route.ts
- apps/postgres-new/utils/telemetry.ts
Adds `toolResults` field to inference telemetry to track the name of the tool that was invoked and whether or not it was successful. Since LLMs can accept multiple tool results in a single message, this is an array. It will be undefined if the input message was not a tool result.
As always no actual content (like args or result message) is sent for privacy reasons.
Example toolResults field:
```
{
...
toolResults: [
{ toolName: 'executeSql', success: true },
],
...
}
```
> feat(telemetry): tool result name and success

- apps/web/components/layout.tsx
Hides unauthenticated header text on mobile.
> Hide header text on mobile

- apps/web/components/providers.tsx
Turns out that service workers are disabled after a [hard reload](https://w3c.github.io/ServiceWorker/#navigator-service-worker-controller) (cmd+shift+r). This PR will detect this and perform a soft reload to re-enable them.
> Fix service worker unavailable after hard reload

- apps/web/next.config.mjs
Switches redirect from postgres.new to database.build to be permanent so the browsers will cache it.
> Adds permanent redirect from legacy domain
